/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.jp.unipe.escala;

import java.awt.Color;

/**
 *
 * @author sidne
 */
public final class Resultado extends javax.swing.JFrame {
    /**
     * Creates new form Resultado
     */
    public int c;

    private Resultado() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    public void saida() {
        if(c < 3){
            p.setText("<html>Houve alguem erro no Programa<br>Reinicie e tente Novamente...</html>");
    
        }else if(c == 3){
            p.setText("<html>A Pontuação do Paciente foi de "+ c +".<br><br>De Acordo "
                    + "Com a Pontuação o paciente esta em: <br>Coma profundo, com 85% "
                    + "de probabilidade de morte e em estado vegetativo.<br><br>"
                    + "A Classificação do Trauma Cranioencefálico do Paciente esta em Estado:<br>"
                    + "Grave, com necessidade de intubação imediata.</html>");
        }else if(c == 4){
            p.setText("<html>A Pontuação do Paciente foi de "+ c +".<br><br>De Acordo "
                    + "Com a Pontuação o paciente esta em: <br>Coma profundo.<br><br>"
                    + "A Classificação do Trauma Cranioencefálico do Paciente esta em Estado:<br>"
                    + "Grave, com necessidade de intubação imediata.</html>");
            
        }else if (c <= 7){
            p.setText("<html>A Pontuação do Paciente foi de "+ c +".<br><br>De Acordo "
                    + "Com a Pontuação o paciente esta em: <br>Coma intermediário.<br><br>"
                    + "A Classificação do Trauma Cranioencefálico do Paciente esta em Estado:<br>"
                    + "Grave, com necessidade de intubação imediata.</html>");
            
        }else if (c <= 11){
            p.setText("<html>A Pontuação do Paciente foi de "+ c +".<br><br>De Acordo "
                    + "Com a Pontuação o paciente esta em: <br>Coma superficial.<br><br>"
                    + "A Classificação do Trauma Cranioencefálico do Paciente esta em Estado:<br>"
                    + "Moderado.</html>");
            
        }else if (c <= 15){
            p.setText("<html>A Pontuação do Paciente foi de "+ c +".<br><br>De Acordo "
                    + "Com a Pontuação o paciente esta em: <br>Normalidade.<br><br>"
                    + "A Classificação do Trauma Cranioencefálico do Paciente esta em Estado:<br>"
                    + "Leve.</html>");
              
        }
        
    }
    public Resultado(int c){
        this.c = c;
        initComponents();
        setTitle("Resultado");
        setSize(850,480);
        setDefaultCloseOperation(Resultado.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        jPanel1.setBackground(Color.white);
        setVisible(true);   
        saida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        p = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(850, 480));

        jButton1.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        p.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        p.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        p.setText("a");
        p.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        p.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        p.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Resultado().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel p;
    // End of variables declaration//GEN-END:variables
}
